
import os
import sys
import random
parse = os.path.abspath('parse_src')
sys.path.insert(1,parse)
import fortran_parse
import json

def fortran_wrap(cmd):
	cmds = cmd.split()
	f_call = cmds[0:6]
	cmds = cmds[6:]
	json_list = [] 
	for cmd in cmds:
		if cmd != '>':
			out_file_name = '/tmp/' + str(random.randint(0,sys.maxsize)) + '.out'
			f_cmd = " ".join(f_call)
			f_cmd += " " + cmd
			f = open(out_file_name, 'w')
			os.system(f_cmd + ' > ' + out_file_name)
			f.close()
			temp = []
			out = []
			for line in open(out_file_name, 'r'):
				print(line)
				if line.strip() != '':
					temp.append(line.strip())
				#print(temp)
			out = fortran_parse.process_parse(temp)
			json_list.append(out)
		#return json.dumps(out)
		else:
			continue
	return json.dumps(json_list)


			

#cmd = 'gfortran -o /Users/DBurke/Documents/Layerlab/parse_webapp/cmd2web/src/web_src/static/js/Parse.exe /Users/DBurke/Documents/Layerlab/parse_webapp/cmd2web/src/web_src/static/js/Parse.f && /Users/DBurke/Documents/Layerlab/parse_webapp/cmd2web/src/web_src/static/js/./Parse.exe  MNELNTVSTNSSDSTKNGGTSNSPDDMDSAAAASHAIKKRTKASRACDQCRKKKIKCDYKDEKGVCSNCQRNGDRCSFDRVPLKRGPSKGYTRSTSHPRTNEIQDHNNSRSYNTFDNSNNTLNNNTGNSGDNGINSNTVPSTPSRSNSVLLPPLTQYIPQAGGIPPSFQNPAIQSTMPAGNIGQQQFWKVPYHEFQHQRKGSIDSLQSDISVRTLNPNEQLSYNTVQQSPITNKHTNDSGNANGSVTGSGSASGSGGYWSFIRTSGLLAPTDDHNGEQTRRSSSIPSLLRNTSNSLLLGGQPQLPPPQQQSQPQAHQQKLQQGQNLYSYSQFSQQQPYNPSISSFGQFAANGFHSRQGSVASEAMSPSAPAMFTSTSTNPVNVAQQTQRPQGQQVPQFSSELDGNKRRQSAPVSVTLSTDRLNGNENNNGEINNNNGSNNSGSSKDTSQHSQESVTTPAALEASSPGSTPQRSTKKRRKSYVSKKTKPKRDSSISITSKDSAHPMTTSSTIAYGQISDVDLIDTYYEFIHVGFPIIPLNKTTLTSDLLLVNTQPISNIHEVNSYVILWFRNSLELLVRVALKQKPGGKFFDNIVGVALSPSNDNNKAGFTTATARDDAEKTRRDSHNEVQDTLEVQSVFIAALNECFQKIVDIHPKFRENNDQISPKIKVIYLSTFILLNYILAFVGYDNSFVLGMSVTIFNEFKLYKLLLFPEPDINDVKPPVDEEVSTGNGNTKTSEFEIGSESAGHMNPSNSPNSMDENISHYSVLFKRLYVLLSVFDSLQSCAFGGPKLLNISIQGSTERFFSNDLGSKWCLEQSQLRLKSVLQSLKLGELMSELTRNRISMNGNRKPGFDITNSSSLLSEYVETQPLSVAQLFCKLLIGKHNFINCLLSLYDSEAGVYSDLTLDLSSKIADSLCSLISIILQVLTLILRLNPTNSIDFNYRPPNPPANNPTVQEGPSAMGSSPVAGNLSAAPPSEGNPDFYKKLLGLKQDTGTILSDLCRGIISPFAIAILHEVYNITELVKQMPTSLISIMMTATTTQNTQDTKKSQDLVMKLSNSMNEVVQITSVLTMIKPFKIFEHELNKPIMSLTGGLSSTTRNDVMWPKSGQGLRESSVMKTLLDERRTSGTQPTTAPVAAEEPRLENVALENFVSIGWKLLDDSELGWY > MSSSPLSKKRRVSGPDPKPGSNCSPAQSVLSEVPSVPTNGMAKNGSEADIDEGLYSRQLYVLGHEAMKRLQTSSVLVSGLRGLGVEIAKNIILGGVKAVTLHDQGTAQWADLSSQFYLREEDIGKNRAEVSQPRLAELNSYVPVTAYTGPLVEDFLSGFQVVVLTNTPLEQLRVGEFCHNRGIKLVVADTRGLFGQLFCDFGEEMILTDSNGEQPLSAMVSMVTKDNPGVVTCLDEARHGFESGDFVSFSEVQGVELNGNQPMEIKVLGPYTFSICDTSNFSDYIRGGIVSQVKVPKKISFKSLVASLAEPDFVVTDFAKFSRPAQLHIGFQALHQFCAQHGRPPRPRNEEDAAELVALAQAVNARALPAVQQNNLDEDLIRKLAYVAAGDLAPINAFIGGLAAQEVMKACSGKFMPIMQWLYFDALECLPEDKEVLTEDKCLQRQNRYDGQVAVFGSDLQEKLGKQKYFLVGAGAIGCELLKNFAMIGLGCGEGGEIIVTDMDTIEKSNLNRQFLFRPWDVTKLKSDTAAAAVRQMNPHIRVTSHQNRVGPDTERIYDDDFFQNLDGVANALDNVDARMYMDRRCVYYRKPLLESGTLGTKGNVQVVIPFLTESYSSSQDPPEKSIPCTLKNFPNAIEHTLQWARDEFEGLFKQPAENVNQYLTDPKFVERTLRLAGTQPLEVLEAVQRSLVLQRPQTWADCVTWACHHWHTQYSNNIRQLLHNFPPDQLTSSGAPFWSGPKRCPHPLTFDVNNPLHLDYVMAAANLFAQTYGLTGSQDRAAVATFLQSVQVPEFTPKSGVKIHVSDQELQSANASVDDSRLEE'
#fortran_wrap(cmd)
